version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/php"
    schedule:
      interval: "daily"
    assignees:
      - "MarkusRodler"

  - package-ecosystem: "docker"
    directory: "/php-composer"
    schedule:
      interval: "daily"
    assignees:
      - "MarkusRodler"

  - package-ecosystem: "docker"
    directory: "/php-composer-xdebug"
    schedule:
      interval: "daily"
    assignees:
      - "MarkusRodler"
